'use client';
import {createContext,useContext,useEffect,useRef,useState,ReactNode} from 'react';
import {toast,Toaster} from 'sonner';
import {Action,Data,apply,seed} from '@/lib/domain';
interface Store {data:Data;ready:boolean;busy:boolean;run:(action:Action,message:string)=>Promise<Data|null>;notice:(message:string)=>void;reset:()=>void;failEmail:boolean;setFailEmail:(v:boolean)=>void;failRetry:boolean;setFailRetry:(v:boolean)=>void;denied:boolean;setDenied:(v:boolean)=>void}
const Context=createContext<Store>(null!);
const KEY='county-parent-education-demo-v1';
export function Provider({children}:{children:ReactNode}){const [data,setData]=useState(seed);const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [failEmail,setFailEmail]=useState(false);const [failRetry,setFailRetry]=useState(false);const [denied,setDenied]=useState(false);const ref=useRef(data);const working=useRef(false);const deniedRef=useRef(denied);deniedRef.current=denied;
useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(saved.version===1&&['cases','classes','enrollments','questions','deliveries'].every(k=>Array.isArray(saved.data?.[k]))){ref.current=saved.data;setData(saved.data)}}}catch{toast.error('Saved sample data could not be loaded. Starting with the original records.')}setReady(true)},[]);
function persist(next:Data){ref.current=next;setData(next);try{localStorage.setItem(KEY,JSON.stringify({version:1,data:next}))}catch{toast.error('Changes are available for this visit, but could not be saved in this browser.')}}
async function run(action:Action,message:string){if(deniedRef.current){toast.error('Staff access is required.');return null}if(working.current)return null;working.current=true;setBusy(true);try{await new Promise(resolve=>setTimeout(resolve,280));if(action.type==='email'&&failEmail){setFailEmail(false);throw Error('Email service unavailable. No recipients were emailed. Please try again.')}const next=apply(ref.current,action.type==='delivery.retry'?{...action,fail:failRetry}:action);if(action.type==='delivery.retry')setFailRetry(false);persist(next);if(action.type==='delivery.retry'&&next.deliveries.find(d=>d.id===action.id)?.status==='Failed')toast.error('Delivery is still unavailable. The certificate remains in Needs attention.');else toast.success(message);return next}catch(error){toast.error(error instanceof Error?error.message:'The change could not be saved. Try again.');return null}finally{setBusy(false);working.current=false}}
function reset(){persist(seed());setFailEmail(false);setFailRetry(false);setDenied(false);toast.success('Original sample records restored.')}return <Context.Provider value={{data,ready,busy,run,notice:toast.success,reset,failEmail,setFailEmail,failRetry,setFailRetry,denied,setDenied}}>{children}<Toaster position="bottom-right" richColors closeButton duration={5000}/></Context.Provider>}
export const useStore=()=>useContext(Context);
export function navigate(path:string){window.location.hash=path}
export function useRoute(){const [route,setRoute]=useState('/');useEffect(()=>{const read=()=>{setRoute(window.location.hash.slice(1)||'/')};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read)},[]);const [path,query]=route.split('?');return{path,params:new URLSearchParams(query),route}}
