'use client';
import {ReactNode,ReactElement,cloneElement,useId,useRef,useState} from 'react';
import {CheckCircle2,ChevronLeft,ChevronRight,Loader2,AlertCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {CaseRecord,payment} from '@/lib/domain';
import {useStore} from './context';
export function Btn({children,primary=false,danger=false,small=false,className='',...props}:React.ComponentProps<typeof Button>&{primary?:boolean;danger?:boolean;small?:boolean}){return <Button className={`btn ${primary?'primary':''} ${danger?'danger':''} ${small?'small':''} ${className}`} {...props}>{children}</Button>}
export function Modal({title,description,children,onClose,wide=false}:{title:string;description?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const previous=useRef<HTMLElement|null>(typeof document!=='undefined'?document.activeElement as HTMLElement:null);return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className={'staff-modal '+(wide?'wide':'')} onCloseAutoFocus={e=>{e.preventDefault();previous.current?.focus()}}><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Review the details below.'}</DialogDescription>{children}</DialogContent></Dialog>}
export function Confirm({title,description,label='Confirm',onConfirm,onClose,danger=false,children}:{title:string;description:string;label?:string;onConfirm:()=>Promise<unknown>|void;onClose:()=>void;danger?:boolean;children?:ReactNode}){const [pending,setPending]=useState(false);return <Modal title={title} description={description} onClose={()=>!pending&&onClose()}>{children}<div className="form-actions"><Btn onClick={onClose} disabled={pending}>Cancel</Btn><Btn primary={!danger} danger={danger} disabled={pending} onClick={async()=>{setPending(true);const result=await onConfirm();setPending(false);if(result!==null&&result!==false)onClose()}}>{pending?<><Loader2 size={16} className="spin"/>Working…</>:label}</Btn></div></Modal>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Status({value}:{value:string}){const tone=['Certified','Paid','Fee waived','Test passed','Sent','Attended','Active'].includes(value)?'green':['Payment needed','Unpaid','Unmarked','Out of attempts','Not activated'].includes(value)?'amber':['Failed','Inactive','Canceled'].includes(value)?'rose':['Enrolled','Ready to certify','In-person testing'].includes(value)?'blue':'neutral';return <Badge tone={tone}>{value==='Sent'?'Sent to broker':value}</Badge>}
export function PaymentActions({record,compact=false}:{record:CaseRecord;compact?:boolean}){const {run,busy}=useStore();return <div className="inline-actions"><Status value={payment(record)}/>{!record.paid&&!record.waived&&<><Btn small disabled={busy} onClick={()=>run({type:'case.payment',id:record.id,paid:true,waived:false},`${record.name} marked paid.`)}>Mark paid</Btn><button disabled={busy} className="text-link" onClick={()=>run({type:'case.payment',id:record.id,paid:false,waived:true},`Fee waived for ${record.name}.`)}>Fee waived</button></>}</div>}
export function Empty({title='No records found',children}:{title?:string;children?:ReactNode}){return <div className="empty"><CheckCircle2 size={26}/><h3>{title}</h3>{children&&<p>{children}</p>}</div>}
export function Notice({children,tone='blue'}:{children:ReactNode;tone?:string}){return <div className={'notice '+tone}><AlertCircle size={18}/><div>{children}</div></div>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){const hintId=useId();const control=cloneElement(children as ReactElement<Record<string,unknown>>,{'aria-label':label,'aria-describedby':hint?hintId:undefined});return <label className="field"><span>{label}</span>{control}{hint&&<small id={hintId}>{hint}</small>}</label>}
export function PageHeading({title,description,action,kicker}:{title:string;description?:string;action?:ReactNode;kicker?:string}){return <div className="page-heading"><div>{kicker&&<div className="eyebrow">{kicker}</div>}<h1 tabIndex={-1}>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function Panel({title,children,action,className=''}:{title?:string;children:ReactNode;action?:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<div className="panel-heading"><h2>{title}</h2>{action}</div>}{children}</section>}
export function Pager({page,total,size=10,onChange}:{page:number;total:number;size?:number;onChange:(p:number)=>void}){const last=Math.max(1,Math.ceil(total/size));return <div className="pagination"><span>{total?`${(page-1)*size+1}–${Math.min(page*size,total)} of ${total}`:'0 records'}</span><div className="inline-actions"><Btn small disabled={page<=1} onClick={()=>onChange(page-1)} aria-label="Previous page"><ChevronLeft size={16}/></Btn><span>Page {page} of {last}</span><Btn small disabled={page>=last} onClick={()=>onChange(page+1)} aria-label="Next page"><ChevronRight size={16}/></Btn></div></div>}
export function Back({href,children}:{href:string;children:ReactNode}){return <a className="back-link" href={'#'+href}><ChevronLeft size={15}/>{children}</a>}
export function Definition({items}:{items:[string,ReactNode][]}){return <dl className="definition">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
