import {Data,Enrollment,date,time} from './domain';
// Small, self-contained PDF writer. Every page is visibly marked as a sample.
export function certificatePdf(data:Data,rows:Enrollment[]):Uint8Array{
 if(!rows.length)throw Error('No existing certificates to download.');
 const text=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'-').replace(/([\\()])/g,'\\$1');
 const objects:string[]=['',''];const add=(s:string)=>{objects.push(s);return objects.length};const regular=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');const pages:number[]=[];
 for(const row of rows){const person=data.cases.find(c=>c.id===row.caseId)!;const cl=data.classes.find(c=>c.id===row.classId)!;const write=(s:string,x:number,y:number,size=12,font='F1')=>`BT /${font} ${size} Tf ${x} ${y} Td (${text(s)}) Tj ET\n`;let stream='0.13 0.24 0.35 RG 2 w 42 42 528 708 re S\n0.13 0.24 0.35 rg\n';stream+=write('PARENT EDUCATION PROGRAM',75,699,22,'F2');stream+=write('Sample Certificate of Completion',75,659,18);stream+='0.65 0.15 0.18 rg\n'+write('SAMPLE - NOT AN OFFICIAL COURT DOCUMENT',75,612,12,'F2');stream+='0.15 0.2 0.26 rg\n'+write('This fictional record confirms completion by:',75,549)+write(person.name,75,509,23,'F2')+write('Case number: '+person.number,75,470,13)+write('Class date: '+date(cl.date),75,425,13)+write('Class time: '+time(cl.start)+' - '+time(cl.end),75,400,13)+write('Language: '+cl.language+'    Format: '+cl.format,75,375,13)+write('Certification date: '+date(row.certified),75,330,13)+write('Created for staff interface demonstration only.',75,167,11)+write('No court filing or official certification is represented by this document.',75,146,10);const content=add(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`);pages.push(add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${regular} 0 R /F2 ${bold} 0 R >> >> /Contents ${content} 0 R >>`))}
 objects[0]='<< /Type /Catalog /Pages 2 0 R >>';objects[1]=`<< /Type /Pages /Kids [${pages.map(p=>p+' 0 R').join(' ')}] /Count ${pages.length} >>`;let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;offsets.slice(1).forEach(n=>pdf+=String(n).padStart(10,'0')+' 00000 n \n');pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf)
}
export function downloadCertificates(data:Data,rows:Enrollment[]){const bytes=certificatePdf(data,rows);const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='sample-parent-education-certificates.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
